# Generated by Django 5.1.4 on 2025-01-10 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_produto_categoria_alter_produto_fornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.FloatField(default=0),
        ),
    ]
