# Generated by Django 5.1.4 on 2025-01-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_produto_estoque_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_de_barras',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together={('codigo_de_barras', 'loja')},
        ),
    ]
