# Generated by Django 5.1.4 on 2025-01-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_userloja'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
