# Generated by Django 5.1.4 on 2025-02-19 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_produto_alterado_por_produto_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='produto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='produto',
            name='codigo_de_barras',
        ),
    ]
